In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.4.6


In [4]:
list1 = [1,2,3]
print(list1)
arr1 = np.array(list1)
print(arr1)

[1, 2, 3]
[1 2 3]


In [5]:
# Two dimensional array

In [8]:
list1 = [1,2,3]
list2 = [4,5,6]

arr2 = np.array([list1, list2])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print("size" , arr2.size)
print("shape" , arr2.shape)
print("Dimension" , arr2.ndim)
print("dtype" , arr2.dtype)

size 6
shape (2, 3)
Dimension 2
dtype int64


In [10]:
# Array initialization methods

In [13]:
zero_arr = np.zeros((3,3))  #create an array full of zeros
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
one_arr = np.ones((3,3))   #create an array full of ones
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
full_arr = np.full((3,3) , 7)   #create an array full of the number passed 
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
ident_arr = np.eye(3)   #create an identity matrix
print(ident_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
print(np.arange(1,10,1)) # creates and array of evenly spaced numbers (start,stop,step)

[1 2 3 4 5 6 7 8 9]


In [31]:
print(np.linspace(1,10,2)) # creates an array of equally spaced number

[ 1. 10.]


In [34]:
rand = np.random.rand(3,3) # Generates a array of random float values
print(rand)

[[0.91873712 0.62059056 0.37293953]
 [0.20713108 0.59157131 0.11018041]
 [0.69384046 0.81116189 0.57089866]]


In [39]:
randint = np.random.randint(1,10 , (3,3))  #Generates array of integers (start,stop,dimension of array)
print(randint)

[[7 5 8]
 [1 6 5]
 [7 1 6]]
